<a href="https://colab.research.google.com/github/Sumit-Patil-01/Python-Programs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#one dimension array
import numpy as np
list1=[11,22,33,44]
array1=np.array(list1)
print(list1)
print(array1)

[11, 22, 33, 44]
[11 22 33 44]


In [ ]:
#two dimensional array
import numpy as np
list1=[[11,22,33],[44,55,66]]
array1=np.array(list1)
print(array1)

[[11 22 33]
 [44 55 66]]


In [ ]:
#three dimensional array
import numpy as np
list1=[[11,22,33],[44,55,66],[77,88,99]]
array1=np.array(list1)
print(array1)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [ ]:
#USE OF RANGE
import numpy as np
array1=np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [ ]:
#RESHAPE USE
import numpy as np
array1=np.arange(11,29).reshape(2,3,3)
print(array1)

[[[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]]


In [ ]:
#ZEROS CREATE MATRIX
import numpy as np
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [ ]:
#ONES CREATE MATRIX
import numpy as np
array1=np.ones(4)
print(array1)

[1. 1. 1. 1.]


Attributes of numPy Array
ndim
shape
size
dtype
itemsize

In [ ]:
import numpy as np
list1=[[11,22,33],[44,55,66]]
array1=np.array(list1)
print(array1)
print(array1.ndim)
print(array1.shape)
print(array1.size)
print(array1.dtype)
print(array1.itemsize)

[[11 22 33]
 [44 55 66]]
2
(2, 3)
6
int64
8


In [ ]:
import numpy as np
list1=[11,22,33]
array1=np.array(list1)
print(array1)
print(array1.ndim)
print(array1.shape)
print(array1.size)
print(array1.dtype)
print(array1.itemsize)

[11 22 33]
1
(3,)
3
int64
8


In [ ]:
import numpy as np
list1=[[[11,22,33],[44,55,66]],[[77,88,99],[88,99,11]]]
array1=np.array(list1)
print(array1)
print(array1.ndim)
print(array1.shape)
print(array1.size)
print(array1.dtype)
print(array1.itemsize)

[[[11 22 33]
  [44 55 66]]

 [[77 88 99]
  [88 99 11]]]
3
(2, 2, 3)
12
int64
8


In [ ]:
import numpy as np
array1=np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])

[20 30]
[20 40 60]
[70 60]
[10 30 50 70]


In [ ]:
import numpy as np
array1=np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
print(array1[1, ])
print(array1[:,1])
print(array1[1:3,1:3])
print(array1[1:3, ])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])
print(array1[0,1:3])


[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 17]
 [26 27]
 [36 37]
 [46 47]]
[26 36]
[[25]
 [35]]
[16 17]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x+y
print(z)

[[12 14]
 [16 18]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x-y
print(z)

[[-10 -10]
 [-10 -10]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x@y
print(z)

[[37 40]
 [85 92]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x*y
print(z)

[[11 24]
 [39 56]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x/y
print(z)

[[0.09090909 0.16666667]
 [0.23076923 0.28571429]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x//y
print(z)

[[0 0]
 [0 0]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x**y
print(z)

[[        1      4096]
 [  1594323 268435456]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])

z=x%y
print(z)

[[1 2]
 [3 4]]


In [ ]:
import numpy as np
lst=[]
n=int(input("Enter number of elements: "))

for i in range(n):
  element=int(input(f"Enter element {i+1}: "))
  lst.append(element)
print("list:",lst)

In [ ]:
s1="SBJAIN"
for i in range(len(s1)):
  print(i,end=" ")
print()
for i in range(len(s1)-1,-1,-1):
  print(s1[i],end="")
print()
for i in range(0,len(s1),2):
  print(s1[i],end=" ")

0 1 2 3 4 5 
NIAJBS
S J I 

In [ ]:
s1=" SBJIAN"
s2=" college"
print(s1+s2)
print(s1*4)

 SBJIAN college
 SBJIAN SBJIAN SBJIAN SBJIAN


In [ ]:
str="hello"
print(str[9::-1])

olleh


In [ ]:
s1="Python Programing Language"
print(s1[:])#full string
print(s1[:5])#0,1,2,3,4 Pytho
print(s1[5:10])#5,6,7,8,9 n Pro
print(s1[::-1])#reverse string print
print(s1[5:])#5 position se ene tak
print(s1[:0:-1])#reverse string upto 1 pos
print(s1[100:999])#null output
print(s1[-1:-8:-1])#-1 -2 -3 -4 -5 -6 -7 egaugna
print(s1[7:17])
print(s1[18:27])
print(s1[-21::-1])

Python Programing Language
Pytho
n Pro
egaugnaL gnimargorP nohtyP
n Programing Language
egaugnaL gnimargorP nohty

egaugna
Programing
Language
nohtyP


In [ ]:
s1="SBJain College 54678"
countspace=0
countdigit=0
countalpha=0
for i in s1:
  if i.isspace():
    countspace+=1
  if i.isspace():
    countdigit+=1
  if i.isalpha():
    countalptha+=1
print(countspace)
print(countdigit)
print(countalpha)


In [ ]:
s="welcome to python programming"
print(s.find("p"))#find first index  position of p ie: 11
print(s.index("p"))#also same
print(s.find("p",12))#find p from 12 index to end
print(s.index("p",12))#same like find
print(s.find("p",1,13))#find p from 1 to 12 index
print(s.index("p",1,13))#same like find
#difference in both
print(s.find("k"))  #give -1
print(s.index("k")) #give error value error
#note find function only available with string
# not available in tupple,list,set but index function available

In [ ]:
="welcome to all python programming "
print(s.split()) #by default split from space and return answer in list
print(s.split("p"))#jaha jaha p waha , ayega
#partition
#print(s.partition())#here must give value for partion nahi tao error
print(s.partition("p"))
#p ke pahele ek part,then  p,then baki part give answer in tupple
#output=>('welcome to all ', 'p', 'ython programming ')
#jony jony wal aexample

In [ ]:
s=" sbjain"
print(s)# its print as it is
print(s.lstrip())#remove left space
#rstrip
s="sbjain     "
print(s)
print(s.rstrip())#its remove but nor see
#to see rstrip
s="sbjain     "
print(len(s))#its count all
print(len(s.rstrip()))#after remove ight space
#strip remove both side space

In [ ]:
#list demo empty list print
my_list1 = []
print(my_list1)
my_list2=list([])
print(my_list2)

[]
[]


In [ ]:
#TUPLE
t=tuple("Hello")
print(t)

('H', 'e', 'l', 'l', 'o')


In [ ]:
L=['a','e','i','o','u']
t=tuple(L)
print(t)

('a', 'e', 'i', 'o', 'u')


In [ ]:
t1=tuple(input("Enter the element:"))


Enter the element:12356


In [ ]:
t1=eval(input("Enter the element:"))
print(t1)

Enter the element:123344
123344


In [ ]:
#create empty tupple
t=(1,)
print(t)
t=tuple()
print(t)


(1,)
()


In [ ]:
#create
t=(1)
print(type(t))
t=(1,)
print(type(t))

<class 'int'>
<class 'tuple'>


In [ ]:
#create different tuple
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)
#nested tuple
t=(1,2,3,(44,55))
print("NESTED TUPPLE=>",t)

(1, 2, 3, 4)
(1.2, 1.2, 1.4, 'a')
NESTED TUPPLE=> (1, 2, 3, (44, 55))


In [ ]:
#take input from user
t1=tuple(input("Enter Element:"))
print(t1)

Enter Element:sumit
('s', 'u', 'm', 'i', 't')


In [ ]:
#convert into tupple
l=[1,2,3]
print(tuple(l))
s="python"
print(tuple(s))
#conver dic to tuple
d={1:"a",2:"b",3:"c"}
print(tuple(d))  #by default key
print(tuple(d.values())) #here value take not keys

(1, 2, 3)
('p', 'y', 't', 'h', 'o', 'n')
(1, 2, 3)
('a', 'b', 'c')


In [ ]:
#packed and unpacked
t=1,2   #packed
print(t)
x,y=(1,2)  #unpacked
print(x,y)

(1, 2)
1 2


In [ ]:
#traversing tuple using for loop
t=(11,22,33,44,55,66)
for i in t:
    print(i,end=" ")

11 22 33 44 55 66 

In [ ]:
t=(11,22,33,44,55,66)
for i in range(len(t)):
    print(t[i],end=" ")

11 22 33 44 55 66 

In [ ]:
#concatenete,replicate,membership
t=(11,22,33)
print(t)
print(id(t))
t=t*3
print(t)
print(id(t))

(11, 22, 33)
132341310613248
(11, 22, 33, 11, 22, 33, 11, 22, 33)
132340379258880


In [ ]:
#2. Concatenate the tuples (1, 2, 3) and (4, 5, 6) and store the result in a new tuple.
t1=(1,2,3)
t2=(4,5,6)
t3=t1+t2
print(t3)

(1, 2, 3, 4, 5, 6)


In [ ]:
#slicing
t=(99,88,77,66,55,44,33,22)
print(t[0:5])  #0 to 3
print(t[::-1])  #reverse
print(t[-1:-5:-1])  #22,33,44,55  start :end-1:step
print(t[::3])
print(t[1:7:2])
print(t[5:8:2])

(99, 88, 77, 66, 55)
(22, 33, 44, 55, 66, 77, 88, 99)
(22, 33, 44, 55)
(99, 66, 33)
(88, 66, 44)
(44, 22)


In [ ]:
#tuple function
t=(11,22,33,44,44,55,44)
print(len(t))  #4
print(max(t))  #55
print(min(t))  #11
print(t.index(44))
print(t.count(44))
print(sum(t))
print(sorted(t))
print(sorted(t,reverse=True))


7
55
11
3
3
253
[11, 22, 33, 44, 44, 44, 55]
[55, 44, 44, 44, 33, 22, 11]


In [ ]:
my_tuple = (10, "hello", 3.14)
print(my_tuple)

(10, 'hello', 3.14)


In [ ]:
#create dictionary
dic={ }  #empty dictionary
print(dic)
print(type(dic))
d=dict()
print(d)
print(type(d))
d={1:"x",2:"y",3:"z"}
print(d)
print(d.keys())
print(d.values())
print(d.items())


{}
<class 'dict'>
{}
<class 'dict'>
{1: 'x', 2: 'y', 3: 'z'}
dict_keys([1, 2, 3])
dict_values(['x', 'y', 'z'])
dict_items([(1, 'x'), (2, 'y'), (3, 'z')])


In [ ]:
#four ways to create dictionary
d1= {"a":"apple","b":"orange","c":"mango"}
d2=dict(a="apple",b="orange",c="mango")
d3=dict([("a","apple"),("b","orange"),("c","mango")])
d4=dict({"a":"apple","b":"orange","c":"mango"})
print(d1==d2==d3==d4)


True


In [ ]:
#check equality
d1={1:99,2:67,3:55}
d2={1:99,2:67,3:55}
print(d1==d2)

True


In [ ]:
d={1:"xx",2:"yy",3:"uu"}
print(d[1])#1 indicate key

xx


In [ ]:
#create empty dictionary and add item
d1=dict()
d1[1]="one"
d1[2]="two"
d1[3]="three"
d1[4]="four"
print(d1)

{1: 'one', 2: 'two', 3: 'three', 4: 'four'}


In [ ]:
#dictionary traversal
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
for i in d:
    print(i,end=" ")#keys print
print()
for i in d:
    print(d[i],end=" ")#value of key print
print()
for i in d.values():
    print(i,end=" ")
print()
for i in d:
    print("key=>",i,"value=>",d[i])#value of key print
for i in d.items():
    print(i,end=" ")#keys print

1 2 3 4 
one two three four 
one two three four 
key=> 1 value=> one
key=> 2 value=> two
key=> 3 value=> three
key=> 4 value=> four
(1, 'one') (2, 'two') (3, 'three') (4, 'four') 

In [ ]:
#update
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d2={5:"five"}
d1.update(d2)
print(d1)
print(d2)

{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{5: 'five'}


In [ ]:
#del
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d2=d1
print(id(d1))
print(id(d2))
d2[5]="five"
print(d1)
print(d2)
del d1[1]
print(d1)
# del d1
print(d1) #error dictionary deleted

139994300356672
139994300356672
{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{2: 'two', 3: 'three', 4: 'four', 5: 'five'}


In [ ]:
#get(some_key,[default value])
d={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
print(d.get(1,"key not present"))#mila tao valu otherwise string print

one


In [ ]:
#update
d1={1: 'one', 2: 'two', 3: 'three', 4: 'four'}
d2={5:"five"}
d1.update(d2)
print(d1)
print(d2)


{1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five'}
{5: 'five'}


In [ ]:
s2="python language"
word=s2.split()
for i in word:
  print(f"{word}:{len(word)}")

['python', 'language']:2
['python', 'language']:2


In [ ]:
s = "python language"
words = s.split()
print("Even length words:")
for word in words:
    if len(word) % 2 == 0:
        print(word)

In [ ]:
s = "Hello World, how are you?"
vowels = "aeiouAEIOU"
vowel_count = 0
for char in s:
    if char in vowels:
        vowel_count += 1
print(f"The string '{s}' has {vowel_count} vowels.")

In [ ]:
def greet(name):
  print(f"Hello, {name}!")

my_string = "Alice"
greet(my_string)
greet("Bob")

In [ ]:
s1 = "Python"
multiplied_string = s1 * 3
print(f"Original string: {s1}")
print(f"Multiplied string (3 times): {multiplied_string}")

s2 = "-"
separator = s2 * 20
print(f"Separator: {separator}")

Original string: Python
Multiplied string (3 times): PythonPythonPython
Separator: --------------------


In [ ]:
my_string = "Hello"
my_string += " World"
print(f"Appended string: {my_string}")

In [ ]:
string1 = "Python"
string2 = " Programming"
concatenated_string = string1 + string2
print(f"Concatenated string: {concatenated_string}")

In [ ]:
main_string = "Welcome to Python Programming"
substring = "Python"
is_present = substring in main_string
print(f"Is '{substring}' present in '{main_string}'? {is_present}")

substring2 = "Java"
is_present2 = substring2 in main_string
print(f"Is '{substring2}' present in '{main_string}'? {is_present2}")

Is 'Python' present in 'Welcome to Python Programming'? True
Is 'Java' present in 'Welcome to Python Programming'? False


In [ ]:
hex_string = "\x48\x65\x6c\x6c\x6f"
print(f"Hexadecimal string: {hex_string}")


newline_hex = "Hello\x0AWorld"
print(f"String with hex newline: {newline_hex}")

In [ ]:
# Printing double quotes with a string variable
my_text = "Python"

# Method 1: Using single quotes to define the string
print(f'She said, "{my_text} is fun!"')

# Method 2: Using escape character within double quotes
print(f"He replied, \"{my_text} is powerful.\"")

# Method 3: Using f-string with mixed quotes (Python 3.6+)
print(f"""The word is "{my_text}"""")

In [ ]:
# Ignoring escape sequences in the string using raw strings

# Without raw string, \n is interpreted as a newline
path_normal = "C:\nUsers\Documents\file.txt"
print(f"Normal string with escape: {path_normal}")

# With raw string (r-prefix), \n is treated as literal characters
path_raw = r"C:\nUsers\Documents\file.txt"
print(f"Raw string ignoring escape: {path_raw}")

# Another example: backslashes are often seen in regular expressions
regex_pattern = r"\d+\s\w+"
print(f"Raw string for regex: {regex_pattern}")

In [ ]:
How to print double quotes with the string variable?